package com.example.fractal.model;

import com.example.fractal.render.BurningShipRenderer;
import com.example.fractal.render.FractalTreeRenderer;
import com.example.fractal.render.JuliaRenderer;
import com.example.fractal.render.KochSnowflakeRenderer;
import com.example.fractal.render.MandelbrotRenderer;
import com.example.fractal.render.SierpinskiCarpetRenderer;

import java.util.Arrays;
import java.util.List;

public final class FractalRegistry {

    private FractalRegistry() {
    }

    public static List<FractalDefinition> createDefinitions() {
        return Arrays.asList(
                new FractalDefinition(
                        "Mandelbrot Set",
                        "Escape-time fractal",
                        "The canonical complex-plane fractal used for deep zoom exploration.",
                        1,
                        9,
                        6,
                        100,
                        new MandelbrotRenderer()
                ),
                new FractalDefinition(
                        "Julia Set",
                        "Escape-time fractal",
                        "A Julia set paired with a fixed complex constant for orbit exploration.",
                        1,
                        9,
                        6,
                        100,
                        new JuliaRenderer()
                ),
                new FractalDefinition(
                        "Burning Ship",
                        "Escape-time fractal",
                        "A sharp escape-time fractal with folded coordinates and flame-like edges.",
                        1,
                        9,
                        6,
                        100,
                        new BurningShipRenderer()
                ),
                new FractalDefinition(
                        "Koch Snowflake",
                        "Rule substitution fractal",
                        "A recursive curve generated by replacing each segment with a four-part motif.",
                        1,
                        7,
                        4,
                        100,
                        new KochSnowflakeRenderer()
                ),
                new FractalDefinition(
                        "Fractal Tree",
                        "Recursive geometry",
                        "A branching recursive structure that makes depth and angle changes easy to inspect.",
                        1,
                        10,
                        7,
                        100,
                        new FractalTreeRenderer()
                ),
                new FractalDefinition(
                        "Sierpinski Carpet",
                        "Recursive geometry",
                        "A planar fractal formed by repeatedly removing the center of a 3x3 grid.",
                        1,
                        6,
                        4,
                        100,
                        new SierpinskiCarpetRenderer()
                )
        );
    }
}