package com.example.fractal.model;

import com.example.fractal.render.BurningShipRenderer;
import com.example.fractal.render.CustomCurveFractalRenderer;
import com.example.fractal.render.CustomFormulaRenderer;
import com.example.fractal.render.FractalTreeRenderer;
import com.example.fractal.render.JuliaRenderer;
import com.example.fractal.render.KochSnowflakeRenderer;
import com.example.fractal.render.MandelbrotRenderer;
import com.example.fractal.render.SierpinskiCarpetRenderer;

import java.util.Arrays;
import java.util.List;

public final class FractalRegistry {

    private FractalRegistry() {
    }

    public static List<FractalDefinition> createDefinitions() {
        return Arrays.asList(
                new FractalDefinition(
                        "Mandelbrot Set",
                        "Escape-Time",
                        "Classic complex-plane fractal for deep zoom exploration.",
                        1,
                        12,
                        6,
                        100,
                        new MandelbrotRenderer()
                ),
                new FractalDefinition(
                        "Julia Set",
                        "Escape-Time",
                        "Julia set driven by a fixed complex constant.",
                        1,
                        12,
                        6,
                        100,
                        new JuliaRenderer()
                ),
                new FractalDefinition(
                        "Burning Ship",
                        "Escape-Time",
                        "Folded-coordinate escape-time fractal with sharp flame-like ridges.",
                        1,
                        12,
                        6,
                        100,
                        new BurningShipRenderer()
                ),
                new FractalDefinition(
                        "Koch Snowflake",
                        "Replacement Curve",
                        "Recursive curve generated by replacing each segment with a four-part motif.",
                        1,
                        16,
                        4,
                        100,
                        new KochSnowflakeRenderer()
                ),
                new FractalDefinition(
                        "Fractal Tree",
                        "Recursive Geometry",
                        "Branching recursive structure for experimenting with depth and shape.",
                        1,
                        20,
                        7,
                        100,
                        new FractalTreeRenderer()
                ),
                new FractalDefinition(
                        "Sierpinski Carpet",
                        "Recursive Geometry",
                        "Planar fractal formed by repeatedly removing center cells.",
                        1,
                        14,
                        4,
                        100,
                        new SierpinskiCarpetRenderer()
                ),
                new FractalDefinition(
                        "Custom Formula",
                        "Custom",
                        "User-defined escape-time formula with a restricted math expression editor.",
                        1,
                        12,
                        6,
                        100,
                        new CustomFormulaRenderer()
                ),
                new FractalDefinition(
                        "Custom Curve",
                        "Custom",
                        "Extract a single contour from an image and recurse it into a fractal pattern.",
                        1,
                        10,
                        5,
                        100,
                        new CustomCurveFractalRenderer()
                )
        );
    }
}
